// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VesselManagementData;

#nullable disable

namespace VesselManagementData.Migrations
{
    [DbContext(typeof(VesselManagemetContext))]
    [Migration("20250226142054_initialEntities")]
    partial class initialEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VesselManagementData.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Giorgio",
                            LastName = "Tomaino"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Tommaso",
                            LastName = "Turigliato"
                        });
                });

            modelBuilder.Entity("VesselManagementData.Models.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Vessels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImoNumber = "IMO 0000001"
                        },
                        new
                        {
                            Id = 2,
                            ImoNumber = "IMO 0000002"
                        });
                });

            modelBuilder.Entity("VesselManagementData.Models.Vessel", b =>
                {
                    b.HasOne("VesselManagementData.Models.Owner", null)
                        .WithMany("Vessels")
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("VesselManagementData.Models.Owner", b =>
                {
                    b.Navigation("Vessels");
                });
#pragma warning restore 612, 618
        }
    }
}
